title: Jaqueline Fernandes   # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Desenvolvedora web, musiscista e entusiasta em ciência de dados. 
  <br><br>
  Repositório de estudo
  <br><br>
  <a href="https://www.linkedin.com/in/jaquelinefernandespb/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-170090729-1 # your Google Analytics tracking ID here
